# Generated by Django 4.0.4 on 2022-05-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
